language: node_js
cache:
  yarn: true
node_js:
  - "12"
script:
  # Ensure that tests pass. Note: "lerna exec"/prepublish script runs on yarn,
  # so there is no need to re-run that here.
  - yarn lint:js
  - yarn lint:styles
  - yarn unit
  # Perform the semantic release on this monorepo after tests have succeeded
  # (see .releaserc for configuration).
  - lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo
# TODO: add deploy stage that updates storybook (for each branch?)
